### PR TITLE
Enable tests to run with Django >= 1.7 and silence warnings

### PR DESCRIPTION
**Pull request by timb07**
This addresses issue #93, and other related changes needed to get tests running again with recent Django versions.

### CODE REVIEW

**Comment by johnraz** [comment]
:+1: this is perfectly working and should be merged :)

**Comment by maxpeterson** [comment]
@timb07 sorry for being so slow getting back to you about this. Can you add Django >= 1.7 to the [.travis.yml](https://github.com/timb07/django-wkhtmltopdf/blob/master/.travis.yml)

**Comment by maxpeterson** [comment]
@timb07 - to be more specific - update .travis.yml to test the appropriate versions of Django

**Comment by maxpeterson** [comment]
@timb07 - I just realised that .travis.yml was updated on #95 so please ignore my last comment and thanks for fixing the tests!

**Pull request merged**
