### PR TITLE
Update changelog for v3.0.0 release

### PR DESCRIPTION
**Pull request by Ian-Foote**

### CODE REVIEW

**Comment by Ian-Foote** [comment]
@maxpeterson @meshy Review?

**Comment by johnraz** [comment]
LGTM.

**Comment by meshy** [comment]
:+1: Happy When Travis Is

**Comment by meshy** [comment]
(Not that travis runs checks against the changelog....)

**Comment by johnraz** [comment]
Would be nice to tag the repo too.

**Comment by Ian-Foote** [comment]
https://github.com/incuna/django-wkhtmltopdf/releases/tag/v3.0.0

**Comment by johnraz** [comment]
awesome thanks :)

**Pull request merged**
