### PR TITLE
[WIP] Decouple PDF generation logic from TemplateView to solve #90

### PR DESCRIPTION
**Pull request by luzfcb**
I'm trying to decouple the PDF generation from TemplateView to solve #90

I'm trying to maintain compatibility. however, it should still have some use cases that i do not think.

Also missing add some tests and tests with other django views, like:

```python
class MyView1(PDFRenderMixin, View):

class MyView2(PDFRenderMixin, ContextMixin, View):

class MyView3(PDFRenderMixin, DetailView):

```

the English is probably bad, I accept willingly corrections
let me know what yours think of it :-)

### CODE REVIEW

**Comment by DebVortex** [comment]
I like the approach you are going here. However, I would vote for completely move the pdf generation out of the Views in e.g. a ``utils.py`` or ``services.py`` which returns the ``InMemoryUploadedFile`` Instance (? Not 100% sure about this approach). Doing so would also allow to e.g. send out pdfs via sendmail more easy.

What do you think about that?

**Comment by johnraz** [comment]
@DebVortex not sure what you mean exactly, this is already decoupled [here](https://github.com/incuna/django-wkhtmltopdf/blob/master/wkhtmltopdf/utils.py#L151).

@luzfcb overall I'd be in favor of this change but I would like the PR to only contain the commits related to the decoupling itself. Please create another PR for the "cleanup" commits. Also having tests would be much appreciated indeed. 👍  good job anyway

**Comment by DebVortex** [comment]
@johnraz thanks for pointing me into that direction. Unfortunately, there is no mention of that function in the documentaiton.

**Comment by johnraz** [comment]
@DebVortex: Feel free to contribute to the documentation ;-)

**Comment by luzfcb** [comment]
@johnraz I will do the "cleanup" as you requested, but probably it will be the weekend.

**Comment by johnraz** [comment]
@luzfcb perfectly fine by me, no hurry, thanks 👍

**Comment by luzfcb** [comment]
@johnraz I have a similar use case as described by @DebVortex: 

starting from the fact that render PDF with wkhtmltopdf is an expensive task (It takes precious seconds), I would like to persist the generated pdf (To then create in my own code an extra check before generating PDF, to return the pdf previously generated if a series of criteria are equal). 

You see any good way to add a hook to execute after the PDF has been generated but before the response is sent?

I thought something like this:

```python
def pre_pdf_response(self, pdf_file_or_in_memory_pdf_file):
     do_some_extra_task_with_the_generated_pdf(pdf_file_or_in_memory_pdf_file)
```

thoughts?

**Comment by DebVortex** [comment]
@luzfcb if you do not have just to generate e.g. a "small invoice" (like most cases for me), having the generation "live" is mostly not crucial and you can have a lot off concurrent at the same time without the user having a notable longer response time.

However, if your pdf gets bigger or you have more images it it, it can as stated take some seconds. The same is, if you have really __a lot of users__ trying to generate PDFs at the same time.

In that case you normaly want to work with some kind of a task queue: you return the user just a "you can download your pdf here, once is processed" (or similar) and use tools like [celery](https://pypi.python.org/pypi/celery) in combination with e.g. [redis](redis.io) to achieve so. If you do not want a big setup with celery and redis, you could take a closer look at [autotask](https://pypi.python.org/pypi/autotask/)

 In the frontend, you could also have some javascript, checking every few seconds a api if the drownload is ready and then prompt the user a link or simply send the pdf via mail or just a mail that the download is ready.

**Comment by johnraz** [comment]
@luzfcb I don't think this is what @DebVortex described, I think he was asking for a way to trigger the generation process outside of a view.
Anyway for your specific question, I think you should be able to do what you want by overriding the `render_to_response` method or something like that, if I get you question right that is ;-)

**Comment by luzfcb** [comment]
@johnraz hum maybe real question is another:

How is the right way to convert `PDFTemplateResponse` instance to a [`BytesIO`](https://docs.python.org/3/library/io.html#io.BytesIO) instance that contains a rendered PDF file?

**Comment by johnraz** [comment]
@luzfcb: I'd say by accessing `response_instance.rendered_content` or `response_instance.content`?

**Comment by luzfcb** [comment]
@johnraz cool. It seems simpler than I had thought. Thanks.

**Comment by luzfcb** [comment]
@johnraz works good. The correct variable to use is `rendered_content`, if you try use `content`, get an error.

a simple example:
```python
import io

class MyPDFTemplateView(PDFTemplateView):
    def render_to_response(self, context, **response_kwargs):
        response_instance = super(MyPDFTemplateView, self).render_to_response(context, **response_kwargs)
        with io.BytesIO(response_instance.rendered_content) as pdf_content:
            with open('test_output.pdf', 'wb') as output_file:
                output_file.write(pdf_content.read())

        return response_instance
```

**Pull request closed without merging**
