### PR TITLE
Properly handle quiet=False case

### PR DESCRIPTION
**Pull request by tclancy**
Addresses #122, don't include `--quiet` on command line if the option is set to `False`.

### CODE REVIEW

**Comment by johnraz** [comment]
Hi @tclancy, thanks a lot for the contrib!

As this is a bug fix, would you mind adding a test case that demonstrates the fix?

Also, did you check that this doesn't apply to other options? Would be nice to make sure `--quiet=False` is the only one that was wrong :-)

**Comment by tclancy** [comment]
@johnraz good points. It looks like [there are a bunch of these options](http://wkhtmltopdf.org/usage/wkhtmltopdf.txt). I will make this much less of a hack and add a test to prove the behavior.

**Comment by johnraz** [comment]
@tclancy looks like the tests are failing :(

**Comment by tclancy** [comment]
Sorry, I'd only done the easy part and updated the code, was going to comment once I added new tests. I am causing one new test failure currently, but on both of my machines I get 8 tests erroring out with or without my changes. The failures all look like this:

```
  File "/Users/tom/Documents/opensource/django-wkhtmltopdf/wkhtmltopdf/utils.py", line 134, in wkhtmltopdf
    return check_output(ck_args, **ck_kwargs)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

This is from me running `make test`. Should I be doing something else? The [failures from Travis](https://travis-ci.org/incuna/django-wkhtmltopdf/jobs/208245304) all look directly related to my change incorrectly appending an argument in the `True` case here which I think I see the fix for, but it's hard to debug given the local failures looking different.

**Comment by tclancy** [comment]
@johnraz I should have checked Travis sooner: just spent an hour hopping between Windows and Mac trying to run down the 8 failures I consistently get (but also got before I made any changes). On Windows they show up as a `CalledProcessError` with no information beyond an error code of `1`. On OSX they all fail with `OSError: [Errno 2]: No such file or directory`. I do see in the Windows output this may be a common issue as it kicks back

```
Exit with code 1 due to network error: ContentAccessDenied
Error: Failed loading page file:///mydrivepath/temp/wkhtmltopdf3xqz3d.html (sometimes it will work just to ignore this error with --load-error-handling ignore)
```

which seems to be [related to PhantomJS](http://stackoverflow.com/questions/35206039/does-a-list-of-all-error-codes-in-phantomjs-exist).

So, after all that, I think this is working, I've extended `test_options_to_args` to check a couple of cases and I've added `--verbose` to the list of `NO_ARGUMENT_OPTIONS` since the test clearly indicated it should be treated that way. Using my fork with `quiet` set to `False` I get feedback like

```
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
Printing pages (6/6)
Done
```

**Comment by johnraz** [comment]
@tclancy awesome job here, this issue has been on everybody's way for a while 👍 

I don't really know for the tests, could it be related to the wkhtml binary not being found in the context of the test runner?
Maybe create a new issue about that so we can give it a later look at.

Cheers!

**Pull request merged**
